version: "2"

services:
  app:
    image: 
    restart: "always"
    expose:
      - 80
    volumes:
      - "./data:/data"
    environment:
      - VIRTUAL_HOST=template.mydomain.com
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=proxy-network
      - LETSENCRYPT_HOST=template.mydomain.com
      - LETSENCRYPT_EMAIL=me@example.com

networks:
  default:
    external:
      name: proxy-network


