version: '2'

services:
  owncloud:
    image: yangxuan8282/armhf-owncloud:9.1.4-apache
    container_name: ownCloud
    restart: always
    expose:
      - 80
    volumes:
      - ./apps:/var/www/html/apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
    environment:
      - VIRTUAL_HOST=disk.mydomain.com
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=proxy-network
      - LETSENCRYPT_HOST=disk.mydomain.com
      - LETSENCRYPT_EMAIL=me@example.com

networks:
  default:
    external:
      name: proxy-network


