version: "2"

services:
  h5ai:
    image: bixidock/h5ai
    restart: "always"
    expose:
      - 80
    volumes:
      - "./www:/var/www"
    environment:
      - VIRTUAL_HOST=release.mydomain.com
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=proxy-network
      - LETSENCRYPT_HOST=release.mydomain.com
      - LETSENCRYPT_EMAIL=me@example.com

networks:
  default:
    external:
      name: proxy-network

