version: "2"

services:
  dl:
    image: nginx
    restart: "always"
    expose:
      - 80
    volumes:
      - "./html:/usr/share/nginx/html"
    environment:
      - VIRTUAL_HOST=dl.mydomain.com
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=proxy-network
      - LETSENCRYPT_HOST=dl.mydomain.com
      - LETSENCRYPT_EMAIL=me@example.com

networks:
  default:
    external:
      name: proxy-network

