version: '2'

services:
  linux-dash:
    image: itxaka/linux-dash-docker
    restart: "always"
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=dash.mydomain.com
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=proxy-network
      - LETSENCRYPT_HOST=dash.mydomain.com
      - LETSENCRYPT_EMAIL=me@example.com

networks:
  default:
    external:
      name: proxy-network

