version: '2'

services:
  drone-server:
    image: drone/drone:0.5
    expose:
      - 8000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_SECRET=
      - VIRTUAL_HOST=ci.mydomain.com
      - VIRTUAL_PORT=8000
      - VIRTUAL_NETWORK=proxy-network
      - LETSENCRYPT_HOST=ci.mydomain.com
      - LETSENCRYPT_EMAIL=me@example.com
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=https://git.mydomain.com

  drone-agent:
    image: drone/drone:0.5
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=

networks:
  default:
    external:
      name: proxy-network

